name: Java CI with Maven

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#    paths:
#      - src
#  pull_request:
#    branches: [ "main" ]
#    paths:
#      - src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
